language: python

services:
    - docker

before_install:
    - docker --version
    - docker-compose --version
    - cp settings/{__,}local_settings.py
    - cp settings/{env_file,.env}
    - echo "GUNICORN_CMD_ARGS=--workers=3" >> settings/.env
    - docker-compose build
    - docker-compose up -d
    - docker ps -a

script:
    - docker-compose exec web python manage.py test

after_failure:
    - docker-compose logs
