language: python

services:
    - docker

before_install:
    - docker login -u "${DOCKER_USERNAME}" --password-stdin <<<"${DOCKER_PASSWORD}"
    - cp settings/{__,}local_settings.py
    - cp settings/{env_file,.env}
    - echo "mysql-password" > ./secrets/mysql_password
    - echo "mysql-root-pwd" > ./secrets/mysql_root_password
    - echo "GUNICORN_CMD_ARGS=--workers=3" >> settings/.env
    - chmod +x ./bin/setup

script:
    - ./bin/setup --no-superuser
    - docker-compose exec web coverage run manage.py test

after_success:
    - docker-compose exec web bash <(curl -s https://codecov.io/bash) 

after_failure:
    - docker-compose logs
