version: '3.3'

services:
    db:
        container_name: mysql
        image: mysql:8
        restart: always
        expose:
            - "3306"
        volumes:
            - mysql_data:/var/lib/mysql
        env_file:
            - ./settings/.env
        environment:    
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
            MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
            MYSQL_DATABASE: campuscats
            MYSQL_USER: app
        secrets:
            - mysql_root_password
            - mysql_password
        # MySQL 8.0 changed this default value but our connector hasn't
        command: --default-authentication-plugin=mysql_native_password

    web:
        container_name: django
        build: campuscats/
        expose:
            - "8000"
        depends_on:
            - db
        env_file:
            - ./settings/.env
        environment:
            DJANGO_SETTINGS_MODULE: local_settings
            PYTHONPATH: /home/app/web/settings
        secrets:
            - site_secret_key
            - mysql_password
        volumes:
            - ./settings:/home/app/web/settings
            - static_files:/home/app/web/static_root
            - media_files:/home/app/web/media_root

    nginx:
        container_name: nginx
        image: nginx:mainline-alpine
        restart: always
        ports: 
            - "80:80"
        depends_on:
            - web
        volumes:
            - ./settings/nginx:/etc/nginx/conf.d
            - static_files:/home/app/web/static_root

secrets:
    mysql_root_password:
        file: ./secrets/mysql_root_password.txt
    site_secret_key:
        file: ./secrets/site_secret_key.txt
    mysql_password:
        file: ./secrets/mysql_password.txt

volumes:
    mysql_data:
    static_files:
    media_files:
