version: '3.3'

services:
    db:
        container_name: mysql
        image: mysql:8
        restart: always
        expose:
            - "3306"
        volumes:
            - mysql_data:/var/lib/mysql
        env_file:
            - env_file
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
            MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
        secrets:
            - mysql_root_password
            - mysql_password
        # MySQL 8.0 changed this default value but our connector hasn't
        command: --default-authentication-plugin=mysql_native_password

    web:
        container_name: django
        build: campuscats/
        expose:
            - "8000"
        depends_on:
            - db
        env_file:
            - env_file
        secrets:
            - site_secret_key
            - mysql_password
            - source: site_settings
              target: site_settings/settings.py
            - source: gunicorn_settings
              target: gunicorn.conf.py
        volumes:
            - static_files:/home/app/web/static_root
            - media_files:/home/app/web/media_root

    nginx:
        container_name: nginx
        image: nginx:mainline-alpine
        restart: always
        ports: 
            - "80:80"
        depends_on:
            - web
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - static_files:/home/app/web/static_root

secrets:
    mysql_root_password:
        file: ./secrets/mysql_root_password.txt
    site_secret_key:
        file: ./secrets/site_secret_key.txt
    mysql_password:
        file: ./secrets/mysql_password.txt
    site_settings:
        file: ./site_settings.py
    gunicorn_settings:
        file: ./gunicorn.conf.py

volumes:
    mysql_data:
    static_files:
    media_files:
