# Generated by Django 3.1.4 on 2021-01-08 00:15

from django.db import migrations, models
import listfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, verbose_name='名字')),
                ('used_names', listfield.fields.ListField(blank=True, max_length=32, verbose_name='曾用名')),
                ('gender', models.BooleanField(blank=True, choices=[(None, '未知'), (0, '男孩子'), (1, '女孩子')], null=True, verbose_name='性别')),
                ('fur', models.BooleanField(blank=True, choices=[(None, '未知'), (0, '长毛'), (1, '短毛')], null=True, verbose_name='发量')),
                ('cat_type', models.PositiveSmallIntegerField(choices=[(None, '未知'), (1, '白猫'), (2, '黑猫'), (3, '奶牛猫'), (4, '狸花猫'), (5, '狸白'), (6, '橘猫'), (7, '橘白'), (8, '三花猫'), (9, '玳瑁猫'), (10, '其他')], verbose_name='毛色')),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='出生年')),
                ('birth_month', models.PositiveSmallIntegerField(blank=True, choices=[(None, '未知'), (1, '春天'), (2, '夏天'), (3, '秋天'), (4, '冬天'), (5, '上半年'), (6, '下半年'), (7, '1月'), (8, '2月'), (9, '3月'), (10, '4月'), (11, '5月'), (12, '6月'), (13, '7月'), (14, '8月'), (15, '9月'), (16, '10月'), (17, '11月'), (18, '12月')], null=True, verbose_name='出生月')),
                ('birth_day', models.PositiveSmallIntegerField(blank=True, choices=[(None, '未知'), (1, '上旬'), (2, '中旬'), (3, '下旬'), (4, '1日'), (5, '2日'), (6, '3日'), (7, '4日'), (8, '5日'), (9, '6日'), (10, '7日'), (11, '8日'), (12, '9日'), (13, '10日'), (14, '11日'), (15, '12日'), (16, '13日'), (17, '14日'), (18, '15日'), (19, '16日'), (20, '17日'), (21, '18日'), (22, '19日'), (23, '20日'), (24, '21日'), (25, '22日'), (26, '23日'), (27, '24日'), (28, '25日'), (29, '26日'), (30, '27日'), (31, '28日'), (32, '29日'), (33, '30日'), (34, '31日')], null=True, verbose_name='出生日')),
                ('neutered', models.BooleanField(blank=True, choices=[(True, '已绝育'), (False, '未绝育'), (None, '未知')], null=True, verbose_name='已绝育')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(None, '状态不明'), (1, '在校流浪'), (2, '失踪'), (3, '回喵星'), (4, '已领养'), (5, '住院')], null=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '猫猫',
                'verbose_name_plural': '猫猫',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CatDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('source', models.PositiveSmallIntegerField(blank=True, choices=[(None, '未知'), (1, '流浪二代'), (2, '弃养'), (3, '校外流浪猫')], null=True, verbose_name='来源')),
                ('last_update', models.DateField(verbose_name='最近更新')),
                ('documented_date', models.DateField(auto_now_add=True, verbose_name='档案创建')),
            ],
            options={
                'verbose_name': '详细信息',
                'verbose_name_plural': '详细信息',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='详细信息')),
                ('date', models.DateField(verbose_name='日期')),
            ],
            options={
                'verbose_name': '记录',
                'verbose_name_plural': '记录',
            },
        ),
    ]
