# Generated by Django 3.1.3 on 2021-04-17 16:17

from django.db import migrations, models
import django.db.models.deletion
import listfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('file', '0002_auto_20210108_0015'),
        ('cat', '0002_auto_20210108_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catdetail',
            name='avatar',
        ),
        migrations.AddField(
            model_name='cat',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='file.photo', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='catdetail',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='cats', related_query_name='cat', to='campus.Location', verbose_name='活动位置'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(blank=True, max_length=8, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='used_names',
            field=listfield.fields.ListField(blank=True, max_length=16, verbose_name='曾用名'),
        ),
    ]
