# Generated by Django 3.1.3 on 2020-11-23 17:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='图像')),
                ('title', models.CharField(blank=True, max_length=8, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('author_name', models.CharField(blank=True, max_length=16, verbose_name='拍摄者名称')),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='拍摄日期')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', related_query_name='photo', to=settings.AUTH_USER_MODEL, verbose_name='拍摄者')),
                ('cats', models.ManyToManyField(related_name='photos', related_query_name='photo', to='cat.Cat', verbose_name='出镜猫猫们')),
            ],
            options={
                'verbose_name': '相片',
                'verbose_name_plural': '相片',
            },
        ),
    ]
