# Generated by Django 3.1.4 on 2021-01-08 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='图像')),
                ('title', models.CharField(blank=True, max_length=8, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('author_name', models.CharField(blank=True, max_length=16, verbose_name='拍摄者名称')),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='拍摄日期')),
            ],
            options={
                'verbose_name': '相片',
                'verbose_name_plural': '相片',
            },
        ),
    ]
