# Generated by Django 3.1.4 on 2021-01-08 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0001_initial'),
        ('cat', '0002_auto_20210108_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', related_query_name='photo', to=settings.AUTH_USER_MODEL, verbose_name='拍摄者'),
        ),
        migrations.AddField(
            model_name='photo',
            name='cats',
            field=models.ManyToManyField(related_name='photos', related_query_name='photo', to='cat.Cat', verbose_name='出镜猫猫们'),
        ),
    ]
